export type CapabilityGroup = 'manufacturing' | 'quality' | 'oem'

export interface CapabilityPageV3 {
  slug: string
  group: CapabilityGroup
  groupLabel: string
  groupHref: string
  eyebrow: string
  title: string
  seoTitle: string
  description: string
  headline: string
  intro: string
  image: string
  pillars: { title: string; detail: string }[]
  process: { title: string; detail: string }[]
  review: string[]
}

export const capabilityPagesV3: CapabilityPageV3[] = [
  {
    slug: 'purification', group: 'manufacturing', groupLabel: 'Manufacturing', groupHref: '/manufacturing', eyebrow: 'Purification technology', title: 'Chemical Purification Technology', seoTitle: 'Chemical Purification Technology | Distillation & Filtration', description: 'Application-led chemical purification covering distillation, filtration, contamination control and qualified transfer routes.', headline: 'Purification engineered around the impurity profile', intro: 'A purification route is useful only when it targets the impurities and variability the finished product must control. We connect feed review, separation, compatible filtration, transfer and release testing to the intended grade.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Distillation strategy', detail: 'Volatility, azeotrope behaviour, thermal sensitivity and target organics shape the separation route.' }, { title: 'Filtration route', detail: 'Filter material, rating, conditioning and transfer are selected around chemical compatibility and particle risk.' }, { title: 'Contamination control', detail: 'Equipment contact, hold time, cleaning, sampling and filling are considered as one control chain.' }, { title: 'Release evidence', detail: 'The product route closes with methods and limits tied to the current controlled specification.' }],
    process: [{ title: 'Define feed variability', detail: 'Review identity, source, impurity pattern and incoming controls.' }, { title: 'Design the separation', detail: 'Choose product-specific purification and compatible equipment.' }, { title: 'Control transfer', detail: 'Protect the material through filtration, hold and filling.' }, { title: 'Verify the lot', detail: 'Release against agreed parameters and document format.' }], review: ['Product and target grade', 'Critical impurities and reporting limits', 'Feedstock or current baseline', 'Required pack, lot size and timing'],
  },
  {
    slug: 'facility', group: 'manufacturing', groupLabel: 'Manufacturing', groupHref: '/manufacturing', eyebrow: 'Production facility', title: 'Chemical Production Facility', seoTitle: 'Chemical Production Facility | Flexible High-Purity Manufacturing', description: 'Production equipment, controlled product routes, clean transfer and flexible batch planning for high-purity chemicals.', headline: 'A production facility organised around controlled product routes', intro: 'Buyers need to know which equipment, controls and release steps are relevant to their material. Facility review therefore follows the product route rather than presenting a generic equipment list as proof of capability.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Product-specific equipment', detail: 'Compatible systems are selected for chemical family, impurity risk and intended scale.' }, { title: 'Controlled utilities', detail: 'Utilities and process conditions are reviewed where they can affect product quality.' }, { title: 'Flexible production', detail: 'Qualification, pilot and routine batches are planned with change and campaign controls in view.' }, { title: 'Engineering records', detail: 'Production, transfer, sampling, testing and filling records connect to the released lot.' }],
    process: [{ title: 'Technical review', detail: 'Match product chemistry and grade to an available route.' }, { title: 'Campaign planning', detail: 'Set batch, cleaning, sampling and scheduling requirements.' }, { title: 'Production control', detail: 'Monitor defined process parameters and material status.' }, { title: 'Release & handoff', detail: 'Complete testing, filling, records and delivery preparation.' }], review: ['Chemical identity and hazards', 'Target grade and batch scale', 'Equipment-contact requirements', 'Qualification and routine schedule'],
  },
  {
    slug: 'packaging', group: 'manufacturing', groupLabel: 'Manufacturing', groupHref: '/manufacturing', eyebrow: 'Packaging capability', title: 'Chemical Packaging Capability', seoTitle: 'Chemical Packaging Capability | Bottles, Drums & IBC Supply', description: 'Chemical packaging review for qualification bottles, production drums, IBCs, closures, labels and export preparation.', headline: 'Packaging is part of the qualified product route', intro: 'Container, closure, headspace, filling, label and transfer can influence both quality and usability. Packaging is therefore reviewed alongside grade, customer handling and destination—not added after the specification is agreed.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Qualification packs', detail: 'Samples should represent the material and contact route intended for production.' }, { title: 'Drum programmes', detail: 'Container material, closure, dispensing, residual handling and site receiving are reviewed.' }, { title: 'IBC routes', detail: 'Connections, storage, consumption rate, return or disposal and transport are aligned.' }, { title: 'Export preparation', detail: 'Pack approval, marks, labels, palletisation and shipment papers follow the product and route.' }],
    process: [{ title: 'Choose the use case', detail: 'Define sampling, qualification or routine production.' }, { title: 'Review contact materials', detail: 'Align container, closure, liner and connection.' }, { title: 'Confirm filling controls', detail: 'Set cleanliness, headspace, identification and records.' }, { title: 'Prepare delivery', detail: 'Match labels, palletisation and documents to destination.' }], review: ['Grade and critical cleanliness attributes', 'Site dispensing and storage', 'Destination and transport mode', 'Volume, order cadence and forecast'],
  },
  {
    slug: 'testing', group: 'quality', groupLabel: 'Quality', groupHref: '/quality', eyebrow: 'Testing capability', title: 'Chemical Testing Capability', seoTitle: 'Chemical Testing Capability | Methods & Product Release', description: 'Product-specific analytical method review for purity, water, trace impurities, residue, particles and release decisions.', headline: 'The test method must be suitable for the release decision', intro: 'A long instrument list does not establish product quality. Testing capability is assessed by method scope, reporting limit, sample handling, calibration, data review and the parameter it supports in the controlled specification.', image: '/images/puretech/quality-control.jpg',
    pillars: [{ title: 'Method fit', detail: 'Technique and sensitivity are matched to the chemical, grade and acceptance limit.' }, { title: 'Sample integrity', detail: 'Sampling, container, preparation and hold time are controlled where results can be affected.' }, { title: 'Data review', detail: 'Results are reviewed against the current specification and documented release route.' }, { title: 'Method communication', detail: 'Customer and supplier align units, limits, method references and reporting format.' }],
    process: [{ title: 'Define the parameter', detail: 'Identify the product risk and acceptance decision.' }, { title: 'Select the method', detail: 'Confirm scope, sensitivity and sample preparation.' }, { title: 'Generate & review data', detail: 'Run controls, evaluate results and investigate exceptions.' }, { title: 'Release or escalate', detail: 'Document conformance or route deviations for review.' }], review: ['Product, grade and parameter list', 'Acceptance limits and methods', 'Reporting-limit expectations', 'CoA result format and qualification stage'],
  },
  {
    slug: 'documentation', group: 'quality', groupLabel: 'Quality', groupHref: '/quality', eyebrow: 'Quality documentation', title: 'Chemical Quality Documentation', seoTitle: 'Chemical Quality Documentation | CoA, SDS & Specifications', description: 'Controlled specifications, CoA formats, SDS, TDS, declarations and qualification documentation for chemical supply.', headline: 'Documents should identify the exact material and decision', intro: 'Specifications, CoA, SDS and technical documents serve different purposes. A useful document pack is current, product-specific, destination-aware and connected to the lot or supply route under review.', image: '/images/puretech/quality-control.jpg',
    pillars: [{ title: 'Controlled specification', detail: 'Defines parameters, units, limits and referenced methods for the agreed grade.' }, { title: 'Certificate of Analysis', detail: 'Connects a supplied lot with reported results or conformance fields.' }, { title: 'Safety Data Sheet', detail: 'Supports market-specific hazard communication, handling and emergency planning.' }, { title: 'Qualification information', detail: 'Company, manufacturing, quality and change information assembled to the project scope.' }],
    process: [{ title: 'Identify the material', detail: 'Confirm chemical, concentration, grade and pack.' }, { title: 'Define the purpose', detail: 'Separate safety, release, technical and regulatory needs.' }, { title: 'Select current files', detail: 'Match revision, market, language and customer scope.' }, { title: 'Control the handoff', detail: 'Record open questions and approved documents.' }], review: ['Exact product and grade', 'Destination and language', 'Required file types', 'Qualification date and customer format'],
  },
  {
    slug: 'compliance', group: 'quality', groupLabel: 'Quality', groupHref: '/quality', eyebrow: 'Compliance support', title: 'Chemical Compliance Support', seoTitle: 'Chemical Compliance Support | Product & Market Review', description: 'Product-, market- and date-specific chemical compliance document review without blanket global claims.', headline: 'Compliance follows the product, market, role and date', intro: 'A supplier cannot responsibly reduce compliance to a universal badge. We review the substance or mixture, destination, use, importer role, current documents and shipment route for the actual transaction.', image: '/images/puretech/pharma-gmp.jpg',
    pillars: [{ title: 'Product identity', detail: 'Substance, concentration, formulation and supplied grade must be exact.' }, { title: 'Market context', detail: 'Destination, use, language and regulatory roles shape the document route.' }, { title: 'Hazard communication', detail: 'Classification, SDS and label elements are checked for the supplied product and market.' }, { title: 'Shipment support', detail: 'Transport and export documents are reviewed with packaging and delivery responsibilities.' }],
    process: [{ title: 'Define transaction', detail: 'Product, customer, destination, use and importer.' }, { title: 'Map requirements', detail: 'Identify documents, labels and open regulatory questions.' }, { title: 'Verify current status', detail: 'Use dated product- and market-specific evidence.' }, { title: 'Record responsibilities', detail: 'Clarify supplier, importer and customer actions.' }], review: ['Product/CAS or formulation', 'Destination and intended use', 'Importer and supply-chain role', 'Required declarations and delivery date'],
  },
  {
    slug: 'traceability', group: 'quality', groupLabel: 'Quality', groupHref: '/quality', eyebrow: 'Batch traceability', title: 'Chemical Batch Traceability', seoTitle: 'Chemical Batch Traceability | Lot & Packaging Records', description: 'Traceability across raw material, production, testing, packaging, release and shipment records for supplied chemical lots.', headline: 'Traceability connects the delivered pack to the released lot', intro: 'A useful traceability chain links material identity, production or campaign records, sampling, testing, filling, pack identification and shipment references. It should be understandable during qualification and usable during an investigation.', image: '/images/puretech/quality-control.jpg',
    pillars: [{ title: 'Material status', detail: 'Incoming identity, lot and disposition connect to the production route.' }, { title: 'Production records', detail: 'Relevant processing, transfer and sampling records identify the manufactured lot.' }, { title: 'Pack identity', detail: 'Filled container, label and closure data connect the physical pack with release.' }, { title: 'Shipment reference', detail: 'Order and delivery records preserve the link through customer receipt.' }],
    process: [{ title: 'Receive & identify', detail: 'Record incoming material and status.' }, { title: 'Process & sample', detail: 'Link manufacturing and representative sampling.' }, { title: 'Test & release', detail: 'Connect results and approval to the lot.' }, { title: 'Fill & ship', detail: 'Carry lot identity through pack and delivery.' }], review: ['Required traceability depth', 'CoA and pack identification format', 'Retention and investigation expectations', 'Customer receiving records'],
  },
  {
    slug: 'private-label', group: 'oem', groupLabel: 'OEM Solutions', groupHref: '/oem-custom-chemical-solutions', eyebrow: 'Private label chemicals', title: 'Private Label Chemical Manufacturing', seoTitle: 'Private Label Chemical Manufacturer | OEM Supply', description: 'Private-label chemical programmes covering product scope, specification, packaging, artwork control, documentation and supply planning.', headline: 'A private-label programme built around controlled ownership', intro: 'Private label is more than applying customer artwork. Product identity, specification, claims, regulatory roles, pack, document ownership, change communication and market responsibilities must be agreed before launch.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Product definition', detail: 'Agree chemical, grade, specification and permitted claims.' }, { title: 'Brand & artwork control', detail: 'Set label ownership, approval, revision and print responsibilities.' }, { title: 'Document route', detail: 'Clarify supplier, brand owner and importer documents for each market.' }, { title: 'Supply programme', detail: 'Plan qualification, MOQ, forecast, inventory assumptions and replenishment.' }],
    process: [{ title: 'Scope the market', detail: 'Define territory, customer, use and brand position.' }, { title: 'Qualify the product', detail: 'Align specification, sample, pack and documents.' }, { title: 'Approve presentation', detail: 'Control artwork, label and document handoff.' }, { title: 'Launch & review', detail: 'Monitor forecast, quality feedback and change needs.' }], review: ['Target product and market', 'Brand/label ownership', 'Pack sizes and annual forecast', 'Required claims and document responsibilities'],
  },
  {
    slug: 'custom-packaging', group: 'oem', groupLabel: 'OEM Solutions', groupHref: '/oem-custom-chemical-solutions', eyebrow: 'Custom packaging', title: 'Custom Chemical Packaging', seoTitle: 'Custom Chemical Packaging | Bottles, Drums & IBC Programmes', description: 'Custom chemical packaging programmes covering container, closure, label, filling, palletisation and market requirements.', headline: 'Custom packaging designed from the customer handling route', intro: 'The useful pack fits chemical compatibility, consumption, storage, dispensing, transport and the customer quality system. We evaluate those constraints before committing to a container or label configuration.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Container & closure', detail: 'Material and sealing route are reviewed for chemical compatibility and handling.' }, { title: 'Filling configuration', detail: 'Fill volume, headspace, connection and cleanliness follow the product need.' }, { title: 'Label system', detail: 'Product identity, hazard information, lot data and customer artwork are controlled.' }, { title: 'Logistics presentation', detail: 'Pallet, overpack, marks and shipment documents follow destination and mode.' }],
    process: [{ title: 'Map site handling', detail: 'Storage, dispensing, opening and consumption.' }, { title: 'Select pack concept', detail: 'Container, closure, fill and label route.' }, { title: 'Qualify configuration', detail: 'Sample, transport and customer review.' }, { title: 'Control production', detail: 'Approved artwork, materials and filling records.' }], review: ['Chemical and target grade', 'Pack size and annual units', 'Closure/connection requirements', 'Label languages and destination markets'],
  },
  {
    slug: 'bulk-supply', group: 'oem', groupLabel: 'OEM Solutions', groupHref: '/oem-custom-chemical-solutions', eyebrow: 'Bulk supply programme', title: 'Bulk Chemical Supply Programme', seoTitle: 'Bulk Chemical Supply | Drums, IBCs & Long-Term Programmes', description: 'Bulk chemical supply planning for drums, IBCs, forecast, site handling, documentation and long-term continuity.', headline: 'Turn bulk demand into a planned supply programme', intro: 'Bulk supply changes receiving, storage, transfer, exposure, safety stock and replenishment. The programme should be designed around the customer site and forecast rather than treated as a larger version of a sample order.', image: '/images/puretech/manufacturing.jpg',
    pillars: [{ title: 'Demand profile', detail: 'Monthly usage, seasonality, shutdowns and safety stock shape the plan.' }, { title: 'Production pack', detail: 'Drum or IBC is selected around site handling, consumption and transport.' }, { title: 'Release route', detail: 'Specification, CoA, SDS, labels and shipment records are agreed.' }, { title: 'Continuity planning', detail: 'Forecast windows, change communication and escalation routes support supply.' }],
    process: [{ title: 'Qualify material', detail: 'Product, grade, specification and representative lot.' }, { title: 'Qualify pack', detail: 'Container, closure, transfer and receiving.' }, { title: 'Plan replenishment', detail: 'Forecast, lead time, order cadence and stock assumptions.' }, { title: 'Review performance', detail: 'Delivery, quality, changes and future demand.' }], review: ['Product, grade and current supplier baseline', 'Monthly and annual volume', 'Site receiving, storage and dispensing', 'Destination, forecast and target start date'],
  },
]

export function findCapabilityPage(group: CapabilityGroup, slug: string) {
  return capabilityPagesV3.find((page) => page.group === group && page.slug === slug)
}
