export interface MarketPage {
  slug: string
  region: string
  name: string
  seoTitle: string
  description: string
  headline: string
  intro: string
  industries: string[]
  requirements: string[]
  applications: { title: string; detail: string }[]
  image: string
}

const standardRequirements = ['Current SDS for the destination', 'Lot-specific CoA format', 'Batch and pack traceability', 'Export and transport document review']

function market(page: Omit<MarketPage, 'requirements'> & { requirements?: string[] }): MarketPage {
  return { ...page, requirements: page.requirements ?? standardRequirements }
}

export const marketPages: MarketPage[] = [
  market({ slug: 'europe', region: 'Regional market', name: 'Europe', seoTitle: 'High-Purity Chemical Supplier for Europe', description: 'High-purity solvents, electronic materials and custom chemical supply planning for European manufacturers and distributors.', headline: 'Chemical supply planning for European industries', intro: 'European qualification work often brings technical specification, REACH context, destination-language SDS, dangerous-goods logistics and supplier continuity into the same review. We structure enquiries around the exact product, market and importer route.', industries: ['Semiconductor & electronics', 'Pharmaceutical manufacturing', 'Specialty chemical processing', 'Analytical & environmental testing'], applications: [{ title: 'Contamination-sensitive manufacturing', detail: 'Electronic solvents and process chemicals screened against application and critical impurity requirements.' }, { title: 'Regulated production', detail: 'Process solvents reviewed with quality documents, change expectations and destination context.' }, { title: 'Distributor programmes', detail: 'Portfolio, pack, label and forecast discussions for an agreed market and customer segment.' }], image: '/images/puretech/manufacturing.jpg' }),
  market({ slug: 'north-america', region: 'Regional market', name: 'North America', seoTitle: 'Specialty Chemical Supplier for North America', description: 'Specialty solvents, electronic materials and documented chemical supply planning for North American industrial customers.', headline: 'High-purity chemical solutions for North American manufacturing', intro: 'North American projects may require close alignment between EHS, quality, procurement, site receiving and technical teams. We begin with the process need, destination, pack and document list before proposing a supply route.', industries: ['Semiconductor & advanced packaging', 'Biotechnology & pharmaceutical', 'Battery & advanced materials', 'Industrial research & manufacturing'], applications: [{ title: 'Advanced manufacturing', detail: 'Application-led electronic and specialty solvent selection for qualification projects.' }, { title: 'Process & formulation', detail: 'High-purity solvents considered around water, residue, impurities, scale and pack.' }, { title: 'Laboratory support', detail: 'Analytical and trace-analysis product routes matched to method and blank requirements.' }], image: '/images/puretech/applications.jpg' }),
  market({ slug: 'japan-korea', region: 'Regional market', name: 'Japan & Korea', seoTitle: 'High-Purity Chemical Supplier for Japan & Korea', description: 'High-purity chemical materials and documented supply programmes for precision electronics and advanced manufacturing in Japan and Korea.', headline: 'Precision chemical supply for Japan and Korea', intro: 'Electronics projects in Japan and Korea frequently place strong emphasis on specification detail, change communication, contamination control and repeatable documentation. Each project is reviewed against the actual customer and import route.', industries: ['Semiconductor manufacturing', 'Display & electronic components', 'Advanced materials', 'Precision industrial processing'], applications: [{ title: 'Electronic cleaning', detail: 'IPA and ethanol routes for contamination-sensitive surface and equipment cleaning.' }, { title: 'Lithography materials', detail: 'PGMEA, PGME and NMP discussions around formulation and process behaviour.' }, { title: 'Advanced materials', detail: 'Specialty solvent supply aligned with moisture, impurity and packaging requirements.' }], image: '/images/puretech/electronic-materials.jpg' }),
  market({ slug: 'southeast-asia', region: 'Regional market', name: 'Southeast Asia', seoTitle: 'High-Purity Chemical Supplier for Southeast Asia', description: 'High-purity solvent and electronic material supply planning for advanced manufacturing projects in Southeast Asia.', headline: 'Chemical solutions for Southeast Asian manufacturing', intro: 'Southeast Asian projects can combine rapid production growth with varied importer, labelling, storage and inland-delivery requirements. Destination and site capability are reviewed before a pack or logistics promise is made.', industries: ['Electronics & semiconductor', 'Pharmaceutical production', 'Industrial manufacturing', 'Regional chemical distribution'], applications: [{ title: 'Electronics production', detail: 'Electronic and high-purity solvents for cleaning, coating and compatible process work.' }, { title: 'Process manufacturing', detail: 'Solvent and packaging selection around consumption, climate, storage and receiving.' }, { title: 'Distribution support', detail: 'Market-specific product, label, documentation and forecast review with qualified partners.' }], image: '/images/puretech/manufacturing.jpg' }),
  market({ slug: 'middle-east', region: 'Regional market', name: 'Middle East', seoTitle: 'High-Purity Chemical Supplier for the Middle East', description: 'High-purity chemical, industrial solvent and distributor supply planning for defined projects serving Middle Eastern markets.', headline: 'Chemical supply planning for Middle Eastern industries', intro: 'Projects serving the Middle East can involve different importer, language, climate, storage, transport and customer-qualification requirements. We confirm the destination and supply-chain roles before proposing product or delivery arrangements.', industries: ['Industrial manufacturing', 'Pharmaceutical production', 'Energy & materials testing', 'Chemical distribution'], applications: [{ title: 'Industrial processing', detail: 'Solvent grade and pack selected around site handling, consumption and environment.' }, { title: 'Analytical testing', detail: 'High-purity reagents reviewed against method, blank and reporting needs.' }, { title: 'Regional distribution', detail: 'Product, label, document and forecast scope defined with qualified partners.' }], image: '/images/puretech/manufacturing.jpg' }),
  market({ slug: 'germany', region: 'Europe', name: 'Germany', seoTitle: 'High-Purity Chemical Supplier Germany | Solvents & Materials', description: 'Chemical supply planning for semiconductor, automotive, pharmaceutical and industrial manufacturing projects in Germany.', headline: 'High-purity chemical solutions for German industry', intro: 'German supplier reviews commonly bring process performance, quality documentation, EHS, REACH context and continuity planning together. We support product and supply discussions for the exact German customer and importer route.', industries: ['Semiconductor & electronics', 'Automotive materials', 'Pharmaceutical manufacturing', 'Specialty chemical processing'], applications: [{ title: 'Electronics processes', detail: 'Electronic-grade IPA, PGMEA and NMP discussions for qualified cleaning and material processes.' }, { title: 'Automotive materials', detail: 'Solvents for compatible coatings, adhesives, surface preparation and controlled testing.' }, { title: 'Pharmaceutical production', detail: 'Process solvents reviewed around use, specification, documentation and destination status.' }], image: '/images/puretech/electronic-materials.jpg' }),
  market({ slug: 'france', region: 'Europe', name: 'France', seoTitle: 'High-Purity Chemical Supplier France | Specialty Solvents', description: 'Specialty solvent and high-purity chemical supply planning for pharmaceutical, cosmetics and research customers in France.', headline: 'Specialty chemical support for French manufacturing and research', intro: 'Projects for France may involve pharmaceutical processing, cosmetics formulation, advanced materials and public or private research. Product grade, SDS language, regulatory context and pack need to be aligned before qualification.', industries: ['Pharmaceutical manufacturing', 'Cosmetics & formulation', 'Research organisations', 'Advanced industrial materials'], applications: [{ title: 'Regulated process solvents', detail: 'Ethanol, IPA, acetone and DMSO routes reviewed against process and document requirements.' }, { title: 'Formulation work', detail: 'Solvent selection around water, residue, organics, compatibility and downstream use.' }, { title: 'Analytical research', detail: 'High-purity and trace-analysis chemicals selected around the actual method.' }], image: '/images/puretech/pharma-gmp.jpg' }),
  market({ slug: 'netherlands', region: 'Europe', name: 'Netherlands', seoTitle: 'Chemical Supplier Netherlands | High-Purity Solvents', description: 'High-purity chemical and distributor supply planning for customers and logistics routes serving the Netherlands.', headline: 'Chemical supply programmes for the Netherlands', intro: 'The Netherlands is often considered in European distribution and logistics planning, but every project still needs a defined importer, storage route, document set and final customer scope. We do not imply local stock until it is contractually established.', industries: ['Chemical distribution', 'Pharmaceutical & biotech', 'Semiconductor ecosystem', 'European logistics programmes'], applications: [{ title: 'Distribution portfolios', detail: 'Product, pack, label and document alignment for a defined customer segment.' }, { title: 'Qualified manufacturing supply', detail: 'High-purity solvents selected around site consumption and quality review.' }, { title: 'Consolidated shipments', detail: 'Shipment planning across compatible products after transport and storage review.' }], image: '/images/puretech/manufacturing.jpg' }),
  market({ slug: 'uk', region: 'Europe', name: 'United Kingdom', seoTitle: 'High-Purity Chemical Supplier UK | Specialty Solvents', description: 'High-purity solvent, pharmaceutical chemical and analytical reagent supply planning for UK organisations.', headline: 'Chemical solutions for UK research and manufacturing', intro: 'UK projects span universities, contract research, pharmaceutical development and advanced manufacturing. The GB or Northern Ireland route, end use, SDS, customs data and importer responsibilities should be made explicit.', industries: ['Universities & research', 'Pharmaceutical & biotech', 'Analytical testing', 'Advanced manufacturing'], applications: [{ title: 'Research workflows', detail: 'High-purity solvents and reagents matched to technique, detector and pack.' }, { title: 'Pharmaceutical development', detail: 'Process-solvent routes considered alongside quality and change expectations.' }, { title: 'Industrial scale-up', detail: 'Qualification pack to drum or IBC discussions with site handling in view.' }], image: '/images/puretech/quality-control.jpg' }),
  market({ slug: 'italy', region: 'Europe', name: 'Italy', seoTitle: 'Specialty Chemical Supplier Italy | High-Purity Solvents', description: 'Specialty solvent and chemical supply planning for pharmaceutical and industrial manufacturers in Italy.', headline: 'High-purity solvent supply for Italian industry', intro: 'Italian enquiries often cross pharmaceutical, coatings, fine chemicals and industrial manufacturing. We organise the review around product function, measurable quality attributes, destination documents and routine delivery format.', industries: ['Pharmaceutical manufacturing', 'Coatings & adhesives', 'Fine chemical processing', 'Industrial production'], applications: [{ title: 'Pharmaceutical process use', detail: 'Ethanol, IPA, acetone and other solvents reviewed around their exact role.' }, { title: 'Coatings & adhesives', detail: 'PGMEA, PGME, esters and ketones considered for formulation behaviour.' }, { title: 'Routine manufacturing', detail: 'Grade and pack selection designed around site consumption and receiving.' }], image: '/images/puretech/high-purity-solvents.jpg' }),
  market({ slug: 'spain', region: 'Europe', name: 'Spain', seoTitle: 'Chemical Supplier Spain | High-Purity Solvents & Reagents', description: 'Chemical supply planning for food testing, pharmaceutical and industrial manufacturing customers in Spain.', headline: 'Chemical solutions for Spanish laboratories and manufacturers', intro: 'Spanish projects may combine food and environmental analysis, pharmaceutical production and industrial solvent demand. Method requirements, destination-language documents and transport conditions should be reviewed together.', industries: ['Food & environmental testing', 'Pharmaceutical manufacturing', 'Industrial processing', 'Research laboratories'], applications: [{ title: 'Food & environmental analysis', detail: 'Solvents, acids and water routes aligned with method blank and detector needs.' }, { title: 'Pharmaceutical operations', detail: 'Process solvents reviewed against use, documentation and qualification stage.' }, { title: 'Industrial solvent supply', detail: 'Drum and IBC discussions based on site handling and replenishment pattern.' }], image: '/images/puretech/trace-analysis.jpg' }),
  market({ slug: 'usa', region: 'North America', name: 'United States', seoTitle: 'Specialty Chemical Supplier USA | High-Purity Solvents', description: 'High-purity solvents, electronic materials and custom chemical supply planning for US manufacturing projects.', headline: 'Specialty chemical solutions for US advanced manufacturing', intro: 'US qualification projects often involve technical, EHS, supplier-quality, procurement and site teams. We provide a structured product and document review; US inventory, registration and importer arrangements are confirmed project by project.', industries: ['Semiconductor & advanced packaging', 'Biotech & pharmaceutical', 'Battery & advanced materials', 'Industrial manufacturing'], applications: [{ title: 'Semiconductor supply', detail: 'Electronic-grade solvent discussions around contamination, pack and qualification.' }, { title: 'Biotech & pharmaceutical', detail: 'Process-solvent selection with quality and market documentation in scope.' }, { title: 'Custom supply programmes', detail: 'Specification, private-label, packaging and forecast discussions for defined projects.' }], image: '/images/puretech/applications.jpg' }),
  market({ slug: 'canada', region: 'North America', name: 'Canada', seoTitle: 'High-Purity Chemical Supplier Canada | Analytical Reagents', description: 'High-purity reagent and specialty solvent supply planning for mining, environmental, research and industrial customers in Canada.', headline: 'Chemical support for Canadian analysis and industry', intro: 'Canadian demand can involve mining assays, environmental monitoring, academic research, pharmaceutical work and industrial processing. The method, language, province, importer and dangerous-goods route need explicit review.', industries: ['Mining & elemental analysis', 'Environmental testing', 'Universities & research', 'Pharmaceutical & industrial'], applications: [{ title: 'Elemental analysis', detail: 'Trace acids and water considered around analyte lists and reporting limits.' }, { title: 'Environmental laboratories', detail: 'Solvents and reagents selected against methods, blanks and throughput.' }, { title: 'Industrial supply', detail: 'Pack and replenishment planning for qualified manufacturing use.' }], image: '/images/puretech/trace-analysis.jpg' }),
  market({ slug: 'japan', region: 'Asia Pacific', name: 'Japan', seoTitle: 'High-Purity Chemical Supplier Japan | Electronic Materials', description: 'High-purity chemical and electronic material supply planning for precision manufacturing projects in Japan.', headline: 'High-purity materials for Japanese precision manufacturing', intro: 'Japanese supplier qualification often places detailed attention on specifications, methods, packaging, change notification and consistent communication. All availability and documentation are confirmed for the actual importer and customer.', industries: ['Semiconductor & electronics', 'Precision components', 'Advanced materials', 'Research & analytical'], applications: [{ title: 'Precision cleaning', detail: 'IPA and ethanol routes reviewed around surface, particles, metals and pack.' }, { title: 'Lithography & coating', detail: 'PGMEA and PGME discussions around formulation and process windows.' }, { title: 'Technical qualification', detail: 'Samples, specifications and document formats aligned before scale-up.' }], image: '/images/puretech/electronic-materials.jpg' }),
  market({ slug: 'south-korea', region: 'Asia Pacific', name: 'South Korea', seoTitle: 'High-Purity Chemical Supplier South Korea | Semiconductor Solvents', description: 'Electronic solvents and advanced material chemical supply planning for semiconductor and display manufacturing in South Korea.', headline: 'Electronic chemical solutions for South Korean manufacturing', intro: 'Semiconductor and display projects in South Korea may require tight impurity control, application testing, pack compatibility and disciplined change communication. Local supply status is established only for the agreed project.', industries: ['Semiconductor fabrication', 'Display manufacturing', 'Advanced packaging', 'Battery materials'], applications: [{ title: 'Wafer & component cleaning', detail: 'Electronic IPA and ethanol routes for qualified cleaning processes.' }, { title: 'Photoresist processing', detail: 'PGMEA, PGME and NMP for compatible coating and process discussions.' }, { title: 'Advanced materials', detail: 'NMP, DMC and specialty solvent selection around moisture and impurity needs.' }], image: '/images/puretech/electronic-materials.jpg' }),
  market({ slug: 'distributor-partnership', region: 'Partner programme', name: 'Global Distribution Partners', seoTitle: 'Chemical Distributor Partnership | Private Label & Supply', description: 'Structured distributor, private-label and regional chemical supply partnership discussions for defined markets.', headline: 'Build a regional chemical programme with clear responsibilities', intro: 'A distributor relationship needs more than a price list. We review market scope, customer segment, regulatory roles, product qualification, labels, documents, forecast and technical escalation before discussing exclusivity or local stock.', industries: ['Specialty chemical distribution', 'Electronic material channels', 'Pharmaceutical raw materials', 'Laboratory & industrial supply'], requirements: ['Defined territory and customer scope', 'Importer and regulatory responsibilities', 'Forecast and inventory assumptions', 'Technical and commercial escalation route'], applications: [{ title: 'Portfolio development', detail: 'Select products around real customer demand rather than a broad undifferentiated list.' }, { title: 'Private-label programmes', detail: 'Review label ownership, pack, documents, artwork control and change route.' }, { title: 'Long-term supply', detail: 'Agree forecast windows, qualification stage, stock assumptions and performance review.' }], image: '/images/puretech/manufacturing.jpg' }),
]

export function findMarketPage(slug: string) {
  return marketPages.find((page) => page.slug === slug)
}
