import Image from 'next/image'
import Link from 'next/link'
import { Container, Eyebrow } from '@/components/ui/index'
import { Reveal } from '@/components/ui/Reveal'
import type { CapabilityPageV3 } from '@/lib/capability-pages-v3'

export function CapabilityPage({ page }: { page: CapabilityPageV3 }) {
  return <>
    <div className="border-b border-[#DCE3EC] bg-[#F7F9FC] py-3"><Container><nav className="flex flex-wrap gap-2 text-[12px] text-[#667085]"><Link href={page.groupHref} className="no-underline hover:text-[#12657B]">{page.groupLabel}</Link><span>›</span><span className="font-medium text-[#102A43]">{page.title}</span></nav></Container></div>
    <section className="relative min-h-[590px] overflow-hidden bg-[#07182D] text-white"><Image src={page.image} alt={`${page.title} industrial capability environment`} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#07182D] via-[#07182D]/92 to-[#07182D]/22" /><Container className="relative z-10 flex min-h-[590px] items-center py-20"><div className="max-w-[780px]"><Eyebrow light>{page.eyebrow}</Eyebrow><h1 className="mt-5 font-serif text-[clamp(39px,5vw,61px)] leading-[1.03] tracking-[-0.8px]">{page.headline}</h1><p className="mt-7 max-w-[710px] text-[16px] leading-[1.78] text-white/72">{page.intro}</p><Link href="#capability" className="mt-9 inline-flex bg-white px-6 py-3.5 text-[13px] font-semibold text-[#102A43] no-underline">Review capability</Link></div></Container></section>
    <section id="capability" className="scroll-mt-24 py-20"><Container><Reveal><Eyebrow>Capability framework</Eyebrow><h2 className="mt-3 font-serif text-[33px] text-[#102A43]">Four parts of the technical review</h2></Reveal><div className="mt-10 grid grid-cols-1 gap-px bg-[#DCE3EC] md:grid-cols-2 lg:grid-cols-4">{page.pillars.map((item, index) => <Reveal key={item.title} delay={index * 45}><article className="h-full min-h-[300px] bg-white p-7"><span className="font-mono text-[10px] font-semibold text-[#2F6B55]">0{index + 1}</span><h3 className="mt-8 text-[15px] font-semibold text-[#102A43]">{item.title}</h3><p className="mt-4 text-[12.7px] leading-[1.72] text-[#475467]">{item.detail}</p></article></Reveal>)}</div></Container></section>
    <section className="bg-[#07182D] py-20 text-white"><Container><Reveal><Eyebrow light>Working route</Eyebrow><h2 className="mt-3 font-serif text-[33px]">A review process with a visible decision at each stage</h2></Reveal><div className="mt-10 grid grid-cols-2 gap-px bg-white/10 lg:grid-cols-4">{page.process.map((item, index) => <Reveal key={item.title} delay={index * 45}><article className="h-full bg-[#07182D] p-6"><span className="font-mono text-[10px] text-[#69C69A]">0{index + 1}</span><h3 className="mt-7 text-[14px] font-semibold">{item.title}</h3><p className="mt-3 text-[12px] leading-[1.68] text-white/48">{item.detail}</p></article></Reveal>)}</div></Container></section>
    <section className="bg-[#F7F9FC] py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[370px_1fr]"><Reveal><div><Eyebrow>Prepare the enquiry</Eyebrow><h2 className="mt-3 font-serif text-[32px] leading-tight text-[#102A43]">Four details make the first review useful</h2><p className="mt-5 text-[14px] leading-[1.75] text-[#475467]">Share the available information even if the project is still at an early stage.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] sm:grid-cols-2">{page.review.map((item, index) => <Reveal key={item} delay={index * 45}><article className="flex h-full gap-4 bg-white p-6"><span className="font-mono text-[10px] text-[#2F6B55]">0{index + 1}</span><p className="text-[13px] leading-[1.65] text-[#344054]">{item}</p></article></Reveal>)}</div></div></Container></section>
    <section className="bg-[#1F5A45] py-20 text-white"><Container><div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-white/48">{page.title}</p><h2 className="mt-4 font-serif text-[35px]">Discuss the requirement with the technical context included</h2><p className="mt-4 max-w-[720px] text-[14px] leading-[1.7] text-white/65">We will review scope, evidence, feasibility, open risks and a practical next step.</p></div><div className="flex flex-wrap gap-3"><Link href={`/contact?subject=${encodeURIComponent(page.title)}`} className="bg-white px-5 py-3 text-[12px] font-semibold text-[#173F31] no-underline">Request review</Link><Link href={page.groupHref} className="border border-white/25 px-5 py-3 text-[12px] font-semibold text-white no-underline">Back to {page.groupLabel}</Link></div></div></Container></section>
  </>
}
