import Image from 'next/image'
import Link from 'next/link'
import { Container, Eyebrow } from '@/components/ui/index'
import { Reveal } from '@/components/ui/Reveal'
import type { ProductPageV3 } from '@/lib/product-pages-v3'

export function PortfolioProductPage({ product }: { product: ProductPageV3 }) {
  const subject = encodeURIComponent(`${product.name} technical review`)
  const stages = [
    ['Application', 'Define the process role, contact materials and observed risk.'],
    ['Specification', 'Agree the attributes, methods, limits and reporting format.'],
    ['Qualification', 'Evaluate a representative sample and production pack route.'],
    ['Routine supply', 'Set forecast, release documents and change communication.'],
  ]

  return <>
    <div className="border-b border-[#DCE3EC] bg-[#F7F9FC] py-3"><Container><nav className="flex flex-wrap gap-2 text-[12px] text-[#667085]"><Link href="/products" className="no-underline hover:text-[#12657B]">Products</Link><span>›</span><Link href={product.categoryHref} className="no-underline hover:text-[#12657B]">{product.categoryLabel}</Link><span>›</span><span className="font-medium text-[#102A43]">{product.name}</span></nav></Container></div>

    <section className="overflow-hidden bg-[#07182D] text-white"><Container><div className="grid min-h-[620px] grid-cols-1 lg:grid-cols-[0.92fr_1.08fr]"><div className="flex flex-col justify-center py-16 pr-0 lg:pr-12"><Eyebrow light>{product.categoryLabel}</Eyebrow><h1 className="mt-4 font-serif text-[clamp(39px,5vw,60px)] leading-[1.03] tracking-[-0.8px]">{product.h1}</h1><p className="mt-6 max-w-[680px] text-[16px] leading-[1.78] text-white/70">{product.shortDescription}</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-[11.5px] text-white/65">{['Application-led selection', 'Controlled document route', 'Packaging & supply review'].map((item) => <span key={item} className="flex items-center gap-2"><span className="text-[#69C69A]">✓</span>{item}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link href={`/contact?subject=${subject}`} className="bg-[#2563EB] px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request technical review</Link><Link href={`/contact?subject=${encodeURIComponent(`${product.name} document request`)}`} className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request documents</Link></div></div><div className="relative min-h-[420px] lg:min-h-[620px]"><Image src={product.image} alt={`${product.name} manufacturing and application environment`} fill priority sizes="(max-width:1024px) 100vw, 55vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#07182D] via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 border border-white/15 bg-[#07182D]/88 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.11em] text-white/40">Portfolio route · {product.id}</p><p className="mt-2 text-[13px] leading-[1.6] text-white/72">{product.grade}. Current specification and availability are confirmed for the exact application and destination.</p></div></div></div></Container></section>

    <section className="py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[0.85fr_1.15fr]"><Reveal><div><Eyebrow>Product overview</Eyebrow><h2 className="mt-3 font-serif text-[34px] leading-tight text-[#102A43]">Start with the work {product.name} must perform</h2><p className="mt-5 text-[14px] leading-[1.78] text-[#475467]">{product.metaDescription}</p><p className="mt-4 text-[13px] leading-[1.72] text-[#667085]">This portfolio page supports initial discovery. It intentionally does not publish a universal numerical specification before the product route, grade and test methods are confirmed.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] sm:grid-cols-2">{product.applications.map((application, index) => <Reveal key={application} delay={index * 45}><article className="h-full bg-white p-6"><span className="font-mono text-[10px] font-semibold text-[#2F6B55]">0{index + 1}</span><h3 className="mt-6 text-[14px] font-semibold capitalize text-[#102A43]">{application}</h3><p className="mt-3 text-[12.5px] leading-[1.68] text-[#475467]">Review suitability against the actual process, critical attributes and qualification baseline.</p></article></Reveal>)}</div></div></Container></section>

    <section className="border-y border-[#E4E7EC] bg-[#F7F9FC] py-20"><Container><Reveal><Eyebrow>Key specification review</Eyebrow><h2 className="mt-3 font-serif text-[32px] text-[#102A43]">The current controlled specification is the starting document</h2><p className="mt-4 max-w-[820px] text-[14px] leading-[1.75] text-[#475467]">Rather than copying nominal values across chemically or commercially different grades, we confirm the following fields for the intended product route.</p></Reveal><div className="mt-10 overflow-hidden border border-[#DCE3EC] bg-white">{[['Product identity', 'Chemical name, composition or agreed blend identity'], ['Grade & critical attributes', product.grade], ['Test methods', 'Product- and parameter-specific methods confirmed during review'], ['Acceptance limits', 'Current controlled specification supplied by request'], ['Supply presentation', 'Container, closure, label and destination reviewed together']].map(([label, value]) => <div key={label} className="grid grid-cols-1 gap-2 border-b border-[#EAECF0] p-5 last:border-b-0 md:grid-cols-[250px_1fr]"><strong className="text-[12.5px] text-[#102A43]">{label}</strong><span className="text-[12.5px] leading-[1.65] text-[#475467]">{value}</span></div>)}</div></Container></section>

    <section className="py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[350px_1fr]"><Reveal><div><Eyebrow>Industries served</Eyebrow><h2 className="mt-3 font-serif text-[32px] leading-tight text-[#102A43]">A product can follow more than one qualification route</h2><p className="mt-5 text-[14px] leading-[1.75] text-[#475467]">Industry labels help discovery; the customer process and controlled specification decide suitability.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] md:grid-cols-3">{product.industries.map((industry, index) => <Reveal key={industry} delay={index * 50}><article className="h-full min-h-[230px] bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">0{index + 1}</span><h3 className="mt-8 text-[15px] font-semibold text-[#102A43]">{industry}</h3><p className="mt-3 text-[12.5px] leading-[1.68] text-[#475467]">Specification, documentation and pack are reviewed for the site and end use.</p></article></Reveal>)}</div></div></Container></section>

    <section className="bg-[#07182D] py-20 text-white"><Container><Reveal><Eyebrow light>Manufacturing & qualification route</Eyebrow><h2 className="mt-3 font-serif text-[33px]">Move from a product name to a controlled supply programme</h2></Reveal><div className="mt-10 grid grid-cols-2 gap-px bg-white/10 lg:grid-cols-4">{stages.map(([title, detail], index) => <Reveal key={title} delay={index * 45}><article className="h-full bg-[#07182D] p-6"><span className="font-mono text-[10px] text-[#69C69A]">0{index + 1}</span><h3 className="mt-7 text-[14px] font-semibold">{title}</h3><p className="mt-3 text-[12px] leading-[1.68] text-white/48">{detail}</p></article></Reveal>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/manufacturing" className="border border-white/20 px-5 py-3 text-[12px] font-semibold text-white no-underline">Manufacturing capability</Link><Link href="/quality" className="border border-white/20 px-5 py-3 text-[12px] font-semibold text-white no-underline">Quality approach</Link></div></Container></section>

    <section className="bg-[#EFF7F3] py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[1fr_0.9fr]"><Reveal><div><Eyebrow>Packaging & documentation</Eyebrow><h2 className="mt-3 font-serif text-[33px] text-[#102A43]">Protect the qualified material through delivery</h2><p className="mt-5 text-[14px] leading-[1.76] text-[#475467]">Packaging and documents are confirmed by product, grade, destination and customer. Listed routes describe the review—not guaranteed availability in every market.</p><div className="mt-8 grid grid-cols-1 gap-px bg-[#C7D9D1] sm:grid-cols-2">{product.packaging.map((pack) => <article key={pack} className="bg-white p-5"><h3 className="text-[13px] font-semibold text-[#102A43]">{pack}</h3><p className="mt-2 text-[11.8px] leading-[1.6] text-[#667085]">Material, closure, filling and logistics confirmed by project.</p></article>)}</div></div></Reveal><Reveal delay={60}><div className="border-t-4 border-[#2F6B55] bg-white p-7"><p className="font-mono text-[10px] uppercase tracking-[0.1em] text-[#2F6B55]">Controlled document route</p><div className="mt-5 divide-y divide-[#EAECF0]">{product.documents.map((document) => <div key={document} className="flex items-center justify-between gap-4 py-4"><span className="text-[12.5px] text-[#344054]">{document}</span><Link href={`/contact?subject=${encodeURIComponent(`${product.name} ${document}`)}`} className="text-[11.5px] font-semibold text-[#12657B] no-underline">Request →</Link></div>)}</div><Link href="/downloads" className="mt-6 inline-flex text-[12px] font-semibold text-[#2F6B55] no-underline">Open document centre →</Link></div></Reveal></div></Container></section>

    <section className="bg-[#1F5A45] py-24 text-white"><Container><div className="text-center"><Eyebrow light>Product enquiry</Eyebrow><h2 className="mx-auto mt-3 max-w-[760px] font-serif text-[clamp(34px,4.5vw,50px)] leading-[1.08]">Discuss {product.name} with the application in view</h2><p className="mx-auto mt-5 max-w-[620px] text-[14.5px] leading-[1.72] text-white/68">Share the use, current specification, destination, pack, annual demand and target qualification date.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href={`/contact?subject=${subject}`} className="bg-white px-6 py-3.5 text-[13px] font-semibold text-[#173F31] no-underline">Request quote</Link><Link href={`/contact?subject=${encodeURIComponent(`${product.name} sample request`)}`} className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request sample</Link><Link href="/products" className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Product finder</Link></div></div></Container></section>
  </>
}
