import Image from 'next/image'
import Link from 'next/link'
import { Container, Eyebrow } from '@/components/ui/index'
import { Reveal } from '@/components/ui/Reveal'
import type { ProductPageV3 } from '@/lib/product-pages-v3'

type PerformanceRow = {
  parameter: string
  relevance: string
  evidence: string
}

type QualificationScenario = {
  title: string
  situation: string
  qualification: string
  evidence: string
}

const performanceByCategory: Record<ProductPageV3['category'], PerformanceRow[]> = {
  electronic: [
    { parameter: 'Assay and organic impurity profile', relevance: 'Helps distinguish the main component from process-relevant organic carryover.', evidence: 'Lot CoA supported by the agreed chromatographic method and controlled specification.' },
    { parameter: 'Water', relevance: 'Can affect drying behaviour, resist processes and moisture-sensitive operations.', evidence: 'Karl Fischer or another agreed method, with the grade-specific limit confirmed before qualification.' },
    { parameter: 'Trace metals', relevance: 'Supports contamination-control review for semiconductor and precision-cleaning processes.', evidence: 'Defined element panel and reporting limits by ICP-MS or an agreed equivalent method.' },
    { parameter: 'Particles and non-volatile residue', relevance: 'Provides a practical view of what may remain on a cleaned or coated surface.', evidence: 'Particle-count and residue methods are selected for the pack route and intended process.' },
    { parameter: 'Container and transfer compatibility', relevance: 'The qualified liquid can still be compromised by an unsuitable closure or transfer path.', evidence: 'Pack material, closure, filling route and sampling plan are documented with the supply proposal.' },
  ],
  solvents: [
    { parameter: 'Identity, assay and organic profile', relevance: 'Confirms the solvent and highlights impurities that may influence reaction, extraction or analysis.', evidence: 'Chromatographic identity and assay against the current controlled specification.' },
    { parameter: 'Water', relevance: 'A practical control point for moisture-sensitive synthesis, extraction and analytical work.', evidence: 'Karl Fischer result on the CoA when included in the agreed grade.' },
    { parameter: 'Acidity, alkalinity and colour', relevance: 'Can reveal degradation, contamination or a mismatch with the intended process.', evidence: 'Product-appropriate methods and grade-specific limits.' },
    { parameter: 'Residue on evaporation', relevance: 'Supports processes where non-volatile contamination may remain after solvent removal.', evidence: 'Gravimetric or agreed compendial method stated in the specification.' },
    { parameter: 'Physical identity checks', relevance: 'Density, refractive index or boiling range can support incoming identification.', evidence: 'Only the identity checks relevant to the exact chemical and grade are reported.' },
  ],
  pharma: [
    { parameter: 'Identity and assay', relevance: 'Establishes material identity and composition before it enters a controlled pharmaceutical process.', evidence: 'Compendial or validated product-specific method, as agreed for the grade.' },
    { parameter: 'Water and process-relevant physical attributes', relevance: 'Supports formulation, reaction and drying consistency.', evidence: 'Release data from the current specification, with method and units clearly stated.' },
    { parameter: 'Specified and unspecified organic impurities', relevance: 'Allows quality teams to compare the profile with process knowledge and material risk.', evidence: 'Chromatographic impurity profile and reporting convention agreed during qualification.' },
    { parameter: 'Residual-solvent and elemental-impurity context', relevance: 'Connects raw-material control with the customer’s ICH Q3C and ICH Q3D risk assessment.', evidence: 'Supplier data and risk information support—but do not replace—the customer’s finished-product assessment.' },
    { parameter: 'Traceability and change communication', relevance: 'Protects a qualified process from undocumented material or supply-route changes.', evidence: 'Lot documents, origin route and change-notification expectations are recorded in the quality agreement.' },
  ],
  trace: [
    { parameter: 'Target-element blank', relevance: 'The reagent contribution should be understood at the concentration range used by the laboratory.', evidence: 'Defined element panel, method reporting limits and lot data by ICP-MS or an agreed technique.' },
    { parameter: 'Acid concentration or assay', relevance: 'Supports reproducible digestion, preservation and dilution chemistry.', evidence: 'Titrimetric or appropriate assay result on the controlled release document.' },
    { parameter: 'Multi-element trace profile', relevance: 'Helps analysts identify elements that could raise preparation blanks or bias low-level results.', evidence: 'Element-by-element report rather than an unsupported general purity statement.' },
    { parameter: 'Container and particulate blank', relevance: 'Packaging and handling can matter as much as bulk purity in trace analysis.', evidence: 'Pack route, sampling practice and any agreed particle or container-blank checks.' },
    { parameter: 'Lot-to-lot blank behaviour', relevance: 'Routine analytical work benefits from a predictable baseline after the method is qualified.', evidence: 'Incoming blank trending remains the laboratory’s control; supplier lot data supports the review.' },
  ],
  custom: [
    { parameter: 'Composition and concentration', relevance: 'Defines what the formulation must deliver at the point of use.', evidence: 'Customer-approved formula, analytical method and release range.' },
    { parameter: 'Critical impurity profile', relevance: 'Focuses control on the contaminants that can affect the actual process.', evidence: 'Risk-based parameter list agreed before scale-up and included in the controlled specification.' },
    { parameter: 'Physical performance window', relevance: 'Properties such as density, pH, viscosity or conductivity may control dosing and handling.', evidence: 'Only relevant attributes are measured, using approved methods and units.' },
    { parameter: 'Container-closure compatibility', relevance: 'Protects composition and cleanliness through storage, transport and dispensing.', evidence: 'Pack study or documented compatibility review for the selected commercial presentation.' },
    { parameter: 'Scale and lot consistency', relevance: 'Links the approved laboratory or pilot sample to repeatable commercial manufacture.', evidence: 'Defined scale-up checks, release records and retained-sample route.' },
  ],
}

const scenariosByCategory: Record<ProductPageV3['category'], QualificationScenario[]> = {
  electronic: [
    { title: 'Precision-cleaning second-source review', situation: 'A European fab support team needs an alternate material without changing the established cleaning sequence.', qualification: 'Compare water, trace-metal, residue and particle controls, then run a representative process trial from the proposed production pack.', evidence: 'Approved specification, lot CoA, sample identity and trial observations are linked in the qualification record.' },
    { title: 'Lithography solvent route assessment', situation: 'A North American process team is screening a solvent for coating, edge-bead or resist-related use.', qualification: 'Map organic impurities, water and non-volatile residue to the process window and dispensing materials.', evidence: 'Supplier data is reviewed alongside the customer’s coating result, defect inspection and incoming-control plan.' },
  ],
  solvents: [
    { title: 'Reaction solvent continuity programme', situation: 'A manufacturer needs a credible second source for a solvent used in a sensitive synthesis step.', qualification: 'Compare identity, assay, water, acidity and process-relevant impurities against both the existing material and reaction outcome.', evidence: 'Side-by-side analytical results, representative batch data and an agreed change-notification route.' },
    { title: 'Bulk pack conversion review', situation: 'A US site is considering a move from drums to a larger package to reduce handling.', qualification: 'Confirm solvent compatibility, closure and transfer materials, sampling plan and receiving controls before changing pack size.', evidence: 'Pack drawing, compatibility review, fill record and site trial are retained with the sourcing decision.' },
  ],
  pharma: [
    { title: 'Pharmaceutical solvent supplier qualification', situation: 'An EU quality team is assessing a solvent used upstream in an API or excipient process.', qualification: 'Review compendial fit, organic-impurity profile, ICH Q3C context, traceability and change-control expectations.', evidence: 'Audit evidence, controlled specification, representative CoAs and the customer’s material risk assessment support approval.' },
    { title: 'Controlled process-aid replacement', situation: 'A North American plant needs supply resilience for a process aid already referenced in internal procedures.', qualification: 'Identify critical material attributes, evaluate the production pack and run an engineering or validation-appropriate trial.', evidence: 'Deviation-free trial records and approved quality documentation are required before routine supply.' },
  ],
  trace: [
    { title: 'ICP-MS reagent blank qualification', situation: 'A laboratory is seeing variability close to its reporting range and is reviewing the acid contribution.', qualification: 'Test the candidate reagent through the actual dilution and digestion procedure using the laboratory’s element panel.', evidence: 'Method blanks, continuing blank trend and supplier lot data are compared; no universal detection limit is assumed.' },
    { title: 'Multi-site analytical standardisation', situation: 'European and US laboratories want a consistent reagent route for comparable trace-element work.', qualification: 'Align pack, sampling, storage, method blank checks and incoming acceptance across sites.', evidence: 'Each laboratory completes local verification while shared supplier documents and lot traceability support comparability.' },
  ],
  custom: [
    { title: 'Customer-defined blend scale-up', situation: 'A formulation that works at laboratory scale must be transferred to controlled commercial manufacture.', qualification: 'Freeze the formula, critical attributes, mixing sequence, sampling method and pack before pilot manufacture.', evidence: 'Approved master record, pilot CoA, compatibility review and customer release decision create the transfer baseline.' },
    { title: 'Private-label portfolio onboarding', situation: 'A European distributor wants a documented solvent range under its own commercial identity.', qualification: 'Align product identity, specification ownership, label/SDS responsibilities, pack artwork and change communication by market.', evidence: 'Signed specification set, approved artwork, document matrix and batch traceability precede launch.' },
  ],
}

export function PortfolioProductPage({ product }: { product: ProductPageV3 }) {
  const subject = encodeURIComponent(`${product.name} technical review`)
  const performanceRows = performanceByCategory[product.category]
  const scenarios = scenariosByCategory[product.category]
  const stages = [
    ['Application', 'Define the process role, contact materials and observed risk.'],
    ['Specification', 'Agree the attributes, methods, limits and reporting format.'],
    ['Qualification', 'Evaluate a representative sample and production pack route.'],
    ['Routine supply', 'Set forecast, release documents and change communication.'],
  ]

  return <>
    <div className="border-b border-[#DCE3EC] bg-[#F7F9FC] py-3"><Container><nav className="flex flex-wrap gap-2 text-[12px] text-[#667085]"><Link href="/products" className="no-underline hover:text-[#12657B]">Products</Link><span>›</span><Link href={product.categoryHref} className="no-underline hover:text-[#12657B]">{product.categoryLabel}</Link><span>›</span><span className="font-medium text-[#102A43]">{product.name}</span></nav></Container></div>

    <section className="overflow-hidden bg-[#07182D] text-white"><Container><div className="grid min-h-[620px] grid-cols-1 lg:grid-cols-[0.92fr_1.08fr]"><div className="flex flex-col justify-center py-16 pr-0 lg:pr-12"><Eyebrow light>{product.categoryLabel}</Eyebrow><h1 className="mt-4 font-serif text-[clamp(39px,5vw,60px)] leading-[1.03] tracking-[-0.8px]">{product.h1}</h1><p className="mt-6 max-w-[680px] text-[16px] leading-[1.78] text-white/70">{product.shortDescription}</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-[11.5px] text-white/65">{['Application-led selection', 'Controlled document route', 'Packaging & supply review'].map((item) => <span key={item} className="flex items-center gap-2"><span className="text-[#69C69A]">✓</span>{item}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link href={`/contact?subject=${subject}`} className="bg-[#2563EB] px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request technical review</Link><Link href={`/contact?subject=${encodeURIComponent(`${product.name} document request`)}`} className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request documents</Link></div></div><div className="relative min-h-[420px] lg:min-h-[620px]"><Image src={product.image} alt={`${product.name} manufacturing and application environment`} fill priority sizes="(max-width:1024px) 100vw, 55vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#07182D] via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 border border-white/15 bg-[#07182D]/88 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.11em] text-white/40">Portfolio route · {product.id}</p><p className="mt-2 text-[13px] leading-[1.6] text-white/72">{product.grade}. Current specification and availability are confirmed for the exact application and destination.</p></div></div></div></Container></section>

    <section className="py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[0.85fr_1.15fr]"><Reveal><div><Eyebrow>Product overview</Eyebrow><h2 className="mt-3 font-serif text-[34px] leading-tight text-[#102A43]">Start with the work {product.name} must perform</h2><p className="mt-5 text-[14px] leading-[1.78] text-[#475467]">{product.metaDescription}</p><p className="mt-4 text-[13px] leading-[1.72] text-[#667085]">This portfolio page supports initial discovery. It intentionally does not publish a universal numerical specification before the product route, grade and test methods are confirmed.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] sm:grid-cols-2">{product.applications.map((application, index) => <Reveal key={application} delay={index * 45}><article className="h-full bg-white p-6"><span className="font-mono text-[10px] font-semibold text-[#2F6B55]">0{index + 1}</span><h3 className="mt-6 text-[14px] font-semibold capitalize text-[#102A43]">{application}</h3><p className="mt-3 text-[12.5px] leading-[1.68] text-[#475467]">Review suitability against the actual process, critical attributes and qualification baseline.</p></article></Reveal>)}</div></div></Container></section>

    <section className="border-y border-[#E4E7EC] bg-[#F7F9FC] py-20"><Container><Reveal><Eyebrow>Performance parameters</Eyebrow><h2 className="mt-3 font-serif text-[32px] text-[#102A43]">Translate “high purity” into parameters the process can qualify</h2><p className="mt-4 max-w-[900px] text-[14px] leading-[1.75] text-[#475467]">The framework below shows the performance questions normally reviewed for {product.name}. Numerical limits are supplied only from the current controlled specification for the selected grade, method and package—never inferred from a portfolio label.</p></Reveal><div className="mt-10 overflow-x-auto border border-[#DCE3EC] bg-white"><div className="min-w-[760px]"><div className="grid grid-cols-[0.8fr_1.25fr_1.25fr] bg-[#102A43] px-5 py-4 text-[10px] font-semibold uppercase tracking-[0.08em] text-white"><span>Parameter</span><span>Why it matters</span><span>Qualification evidence</span></div>{performanceRows.map((row) => <div key={row.parameter} className="grid grid-cols-[0.8fr_1.25fr_1.25fr] gap-5 border-b border-[#EAECF0] px-5 py-5 last:border-b-0"><strong className="text-[12.5px] leading-[1.55] text-[#102A43]">{row.parameter}</strong><span className="text-[12px] leading-[1.65] text-[#475467]">{row.relevance}</span><span className="text-[12px] leading-[1.65] text-[#667085]">{row.evidence}</span></div>)}</div></div><p className="mt-4 text-[11.5px] leading-[1.65] text-[#667085]">Grade under review: {product.grade}. Final parameters, methods, limits and reporting units are agreed before sample qualification.</p></Container></section>

    <section className="py-20"><Container><Reveal><Eyebrow>Application qualification scenarios</Eyebrow><h2 className="mt-3 max-w-[820px] font-serif text-[32px] leading-tight text-[#102A43]">How technical and procurement teams can evaluate this product</h2><p className="mt-4 max-w-[860px] text-[14px] leading-[1.75] text-[#475467]">These are representative composite scenarios—not named customer claims. They show a practical evidence route for common European and North American sourcing questions.</p></Reveal><div className="mt-10 grid grid-cols-1 gap-5 lg:grid-cols-2">{scenarios.map((scenario, index) => <Reveal key={scenario.title} delay={index * 60}><article className="h-full border border-[#DCE3EC] bg-white p-7"><p className="font-mono text-[10px] uppercase tracking-[0.08em] text-[#2F6B55]">Qualification scenario 0{index + 1}</p><h3 className="mt-4 font-serif text-[23px] text-[#102A43]">{scenario.title}</h3><dl className="mt-6 space-y-5"><div><dt className="text-[11px] font-semibold uppercase tracking-[0.07em] text-[#667085]">Situation</dt><dd className="mt-2 text-[12.5px] leading-[1.7] text-[#475467]">{scenario.situation}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-[0.07em] text-[#667085]">Qualification route</dt><dd className="mt-2 text-[12.5px] leading-[1.7] text-[#475467]">{scenario.qualification}</dd></div><div><dt className="text-[11px] font-semibold uppercase tracking-[0.07em] text-[#667085]">Evidence retained</dt><dd className="mt-2 text-[12.5px] leading-[1.7] text-[#475467]">{scenario.evidence}</dd></div></dl></article></Reveal>)}</div></Container></section>

    <section className="border-t border-[#E4E7EC] py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[350px_1fr]"><Reveal><div><Eyebrow>Industries served</Eyebrow><h2 className="mt-3 font-serif text-[32px] leading-tight text-[#102A43]">A product can follow more than one qualification route</h2><p className="mt-5 text-[14px] leading-[1.75] text-[#475467]">Industry labels help discovery; the customer process and controlled specification decide suitability.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] md:grid-cols-3">{product.industries.map((industry, index) => <Reveal key={industry} delay={index * 50}><article className="h-full min-h-[230px] bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">0{index + 1}</span><h3 className="mt-8 text-[15px] font-semibold text-[#102A43]">{industry}</h3><p className="mt-3 text-[12.5px] leading-[1.68] text-[#475467]">Specification, documentation and pack are reviewed for the site and end use.</p></article></Reveal>)}</div></div></Container></section>

    <section className="bg-[#07182D] py-20 text-white"><Container><Reveal><Eyebrow light>Manufacturing & qualification route</Eyebrow><h2 className="mt-3 font-serif text-[33px]">Move from a product name to a controlled supply programme</h2></Reveal><div className="mt-10 grid grid-cols-2 gap-px bg-white/10 lg:grid-cols-4">{stages.map(([title, detail], index) => <Reveal key={title} delay={index * 45}><article className="h-full bg-[#07182D] p-6"><span className="font-mono text-[10px] text-[#69C69A]">0{index + 1}</span><h3 className="mt-7 text-[14px] font-semibold">{title}</h3><p className="mt-3 text-[12px] leading-[1.68] text-white/48">{detail}</p></article></Reveal>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/manufacturing" className="border border-white/20 px-5 py-3 text-[12px] font-semibold text-white no-underline">Manufacturing capability</Link><Link href="/quality" className="border border-white/20 px-5 py-3 text-[12px] font-semibold text-white no-underline">Quality approach</Link></div></Container></section>

    <section className="bg-[#EFF7F3] py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[1fr_0.9fr]"><Reveal><div><Eyebrow>Packaging & documentation</Eyebrow><h2 className="mt-3 font-serif text-[33px] text-[#102A43]">Protect the qualified material through delivery</h2><p className="mt-5 text-[14px] leading-[1.76] text-[#475467]">Packaging and documents are confirmed by product, grade, destination and customer. Listed routes describe the review—not guaranteed availability in every market.</p><div className="mt-8 grid grid-cols-1 gap-px bg-[#C7D9D1] sm:grid-cols-2">{product.packaging.map((pack) => <article key={pack} className="bg-white p-5"><h3 className="text-[13px] font-semibold text-[#102A43]">{pack}</h3><p className="mt-2 text-[11.8px] leading-[1.6] text-[#667085]">Material, closure, filling and logistics confirmed by project.</p></article>)}</div></div></Reveal><Reveal delay={60}><div className="border-t-4 border-[#2F6B55] bg-white p-7"><p className="font-mono text-[10px] uppercase tracking-[0.1em] text-[#2F6B55]">Controlled document route</p><div className="mt-5 divide-y divide-[#EAECF0]">{product.documents.map((document) => <div key={document} className="flex items-center justify-between gap-4 py-4"><span className="text-[12.5px] text-[#344054]">{document}</span><Link href={`/contact?subject=${encodeURIComponent(`${product.name} ${document}`)}`} className="text-[11.5px] font-semibold text-[#12657B] no-underline">Request →</Link></div>)}</div><Link href="/downloads" className="mt-6 inline-flex text-[12px] font-semibold text-[#2F6B55] no-underline">Open document centre →</Link></div></Reveal></div></Container></section>

    <section className="bg-[#1F5A45] py-24 text-white"><Container><div className="text-center"><Eyebrow light>Product enquiry</Eyebrow><h2 className="mx-auto mt-3 max-w-[760px] font-serif text-[clamp(34px,4.5vw,50px)] leading-[1.08]">Discuss {product.name} with the application in view</h2><p className="mx-auto mt-5 max-w-[620px] text-[14.5px] leading-[1.72] text-white/68">Share the use, current specification, destination, pack, annual demand and target qualification date.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href={`/contact?subject=${subject}`} className="bg-white px-6 py-3.5 text-[13px] font-semibold text-[#173F31] no-underline">Request quote</Link><Link href={`/contact?subject=${encodeURIComponent(`${product.name} sample request`)}`} className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Request sample</Link><Link href="/products" className="border border-white/25 px-6 py-3.5 text-[13px] font-semibold text-white no-underline">Product finder</Link></div></div></Container></section>
  </>
}
