import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Container, Eyebrow } from '@/components/ui/index'
import { Reveal } from '@/components/ui/Reveal'
import { findMarketPage, marketPages } from '@/lib/market-pages'

type Params = Promise<{ slug: string }>

export function generateStaticParams() { return marketPages.map((page) => ({ slug: page.slug })) }

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { slug } = await params
  const page = findMarketPage(slug)
  if (!page) return { title: 'Market Page Not Found' }
  return { title: page.seoTitle, description: page.description, alternates: { canonical: `https://puretechmaterials.com/markets/${page.slug}` } }
}

const solutionGroups = [
  { title: 'Electronic & advanced materials', products: [['Electronic Grade IPA', '/products/electronic-grade-ipa', 'Cleaning and contamination-sensitive processes'], ['PGMEA', '/products/pgmea', 'Lithography and compatible coating systems'], ['NMP', '/products/nmp-solvent', 'Electronics and advanced-material processing']] },
  { title: 'High-purity & process solvents', products: [['High-Purity IPA', '/products/ipa-solvent', 'Cleaning, process and formulation work'], ['Ethanol', '/products/ethanol-solvent', 'Process, extraction and controlled cleaning'], ['Acetone', '/products/acetone', 'Compatible cleaning, washing and work-up']] },
  { title: 'Trace analysis chemicals', products: [['Trace Grade Nitric Acid', '/products/trace-grade-nitric-acid', 'Digestion and elemental sample preparation'], ['Trace Grade Hydrochloric Acid', '/products/trace-grade-hydrochloric-acid', 'Stabilisation and defined digestion chemistry'], ['Ultrapure Water', '/products/ultrapure-water', 'Blank, dilution and contamination-sensitive work']] },
]

export default async function MarketDetailPage({ params }: { params: Params }) {
  const { slug } = await params
  const page = findMarketPage(slug)
  if (!page) notFound()
  return <>
    <div className="border-b border-[#DCE3EC] bg-[#F7F9FC] py-3"><Container><nav className="flex flex-wrap gap-2 text-[12px] text-[#667085]"><Link href="/markets" className="no-underline hover:text-[#12657B]">Global Markets</Link><span>›</span><span className="font-medium text-[#102A43]">{page.name}</span></nav></Container></div>
    <section className="relative min-h-[610px] overflow-hidden bg-[#07182D] text-white"><Image src={page.image} alt={`${page.name} industrial chemical market and application environment`} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#07182D] via-[#07182D]/92 to-[#07182D]/22" /><Container className="relative z-10 flex min-h-[610px] items-center py-20"><div className="max-w-[760px]"><Eyebrow light>{page.region}</Eyebrow><h1 className="mt-5 font-serif text-[clamp(39px,5vw,62px)] leading-[1.02] tracking-[-0.85px]">{page.headline}</h1><p className="mt-7 max-w-[700px] text-[16px] leading-[1.78] text-white/72">{page.intro}</p><Link href={`/contact?subject=${encodeURIComponent(`${page.name} market supply enquiry`)}`} className="mt-9 inline-flex bg-white px-6 py-3.5 text-[13px] font-semibold text-[#102A43] no-underline">Request regional review</Link></div></Container></section>
    <section className="border-b border-[#D8E5DF] bg-[#EFF7F3] py-8"><Container><p className="max-w-[960px] text-[13px] leading-[1.72] text-[#315848]"><strong>Market-scope note:</strong> This page describes potential support for projects serving {page.name}. It does not claim a local entity, warehouse, registration, distributor, inventory position or established customer relationship.</p></Container></section>
    <section className="py-20"><Container><Reveal><Eyebrow>Regional market understanding</Eyebrow><h2 className="mt-3 font-serif text-[33px] text-[#102A43]">Three parts of a useful {page.name} supply brief</h2></Reveal><div className="mt-10 grid grid-cols-1 gap-px bg-[#DCE3EC] lg:grid-cols-3"><article className="bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">01 · Industry focus</span><div className="mt-7 flex flex-wrap gap-2">{page.industries.map((item) => <span key={item} className="border border-[#DCE3EC] px-3 py-2 text-[11.5px] text-[#475467]">{item}</span>)}</div></article><article className="bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">02 · Product demand</span><p className="mt-7 text-[13px] leading-[1.75] text-[#475467]">Prioritise the small set of electronic materials, process solvents or analytical chemicals that fit the local customer and application.</p></article><article className="bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">03 · Supply requirements</span><ul className="mt-7 space-y-3">{page.requirements.map((item) => <li key={item} className="flex gap-2 text-[12.5px] leading-[1.55] text-[#475467]"><span className="text-[#2F6B55]">✓</span>{item}</li>)}</ul></article></div></Container></section>
    <section className="border-y border-[#E4E7EC] bg-[#F7F9FC] py-20"><Container><Reveal><Eyebrow>Recommended product routes</Eyebrow><h2 className="mt-3 font-serif text-[33px] text-[#102A43]">Begin with the application, then narrow the product</h2><p className="mt-4 max-w-[780px] text-[14px] leading-[1.75] text-[#475467]">These are discovery routes, not statements that every grade or pack is available in {page.name}. Confirm current product and destination status during enquiry.</p></Reveal><div className="mt-10 grid grid-cols-1 gap-5 lg:grid-cols-3">{solutionGroups.map((group, index) => <Reveal key={group.title} delay={index * 50}><article className="h-full border border-[#DCE3EC] bg-white p-6"><span className="font-mono text-[10px] text-[#2F6B55]">0{index + 1}</span><h3 className="mt-6 text-[15px] font-semibold text-[#102A43]">{group.title}</h3><div className="mt-5 divide-y divide-[#EAECF0]">{group.products.map(([name, href, use]) => <Link key={name} href={href} className="block py-4 text-[#102A43] no-underline"><strong className="text-[12.5px] hover:text-[#12657B]">{name} →</strong><span className="mt-1 block text-[11.5px] leading-[1.55] text-[#667085]">{use}</span></Link>)}</div></article></Reveal>)}</div></Container></section>
    <section className="py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[350px_1fr]"><Reveal><div><Eyebrow>Regional applications</Eyebrow><h2 className="mt-3 font-serif text-[32px] leading-tight text-[#102A43]">Chemical discussions shaped by local industry</h2><p className="mt-5 text-[14px] leading-[1.75] text-[#475467]">The application decides which specification, document and supply questions deserve attention.</p></div></Reveal><div className="grid grid-cols-1 gap-px bg-[#DCE3EC] md:grid-cols-3">{page.applications.map((item, index) => <Reveal key={item.title} delay={index * 50}><article className="h-full bg-white p-7"><span className="font-mono text-[10px] text-[#2F6B55]">0{index + 1}</span><h3 className="mt-8 text-[14px] font-semibold text-[#102A43]">{item.title}</h3><p className="mt-3 text-[12.5px] leading-[1.7] text-[#475467]">{item.detail}</p></article></Reveal>)}</div></div></Container></section>
    <section className="bg-[#EFF7F3] py-20"><Container><div className="grid grid-cols-1 gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><Reveal><div><Eyebrow>Quality documentation</Eyebrow><h2 className="mt-3 font-serif text-[34px] leading-tight text-[#102A43]">Review the file in the context of the destination</h2><p className="mt-5 text-[14px] leading-[1.78] text-[#475467]">CoA, specification, SDS, traceability and export records answer different questions. Current product- and market-specific files are supplied through a controlled request route.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/compliance" className="bg-[#1F5A45] px-5 py-3 text-[12px] font-semibold text-white no-underline">Compliance guidance</Link><Link href="/downloads" className="border border-[#2F6B55] px-5 py-3 text-[12px] font-semibold text-[#2F6B55] no-underline">Document centre</Link></div></div></Reveal><div className="relative min-h-[470px] overflow-hidden"><Image src="/images/puretech/quality-control.jpg" alt={`Quality documentation and analytical review for ${page.name} chemical projects`} fill sizes="(max-width:1024px) 100vw, 45vw" className="object-cover" /></div></div></Container></section>
    <section className="bg-[#07182D] py-20 text-white"><Container><Reveal><Eyebrow light>Reliable global supply chain</Eyebrow><h2 className="mt-3 font-serif text-[33px]">Build the delivery route before promising the date</h2><p className="mt-4 max-w-[780px] text-[14px] leading-[1.75] text-white/58">For {page.name}, product, pack, dangerous-goods classification, documents, importer responsibilities, transport mode and inland delivery conditions are reviewed as one programme.</p></Reveal><div className="mt-10 grid grid-cols-2 gap-px bg-white/10 lg:grid-cols-4">{['Manufacturing', 'Quality control', 'Export packaging', 'International delivery'].map((item, index) => <article key={item} className="bg-[#07182D] p-6"><span className="font-mono text-[10px] text-[#69C69A]">0{index + 1}</span><h3 className="mt-7 text-[13.5px] font-semibold">{item}</h3></article>)}</div><Link href="/global-chemical-supply" className="mt-8 inline-flex border border-white/20 px-5 py-3 text-[12px] font-semibold text-white no-underline">Review global supply capability →</Link></Container></section>
    <section className="py-20"><Container><div className="grid grid-cols-1 gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><Eyebrow>Partner programme</Eyebrow><h2 className="mt-3 font-serif text-[32px] text-[#102A43]">Develop the market with defined roles</h2><p className="mt-4 max-w-[780px] text-[14px] leading-[1.75] text-[#475467]">Distributor cooperation, private label, possible regional stock planning, technical support and long-term supply are discussed only after territory, customers, responsibilities and forecast assumptions are clear.</p></div><Link href="/markets/distributor-partnership" className="bg-[#1F5A45] px-6 py-3.5 text-[12.5px] font-semibold text-white no-underline">Partner with PURETECHMATERIALS</Link></div></Container></section>
    <section className="bg-[#1F5A45] py-20 text-white"><Container><div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.13em] text-white/50">{page.name} market enquiry</p><h2 className="mt-4 font-serif text-[35px]">Need a reliable chemical supply partner?</h2><p className="mt-4 max-w-[720px] text-[14px] leading-[1.7] text-white/65">Share the product, grade, destination, use, pack, annual volume, qualification stage and required documents.</p></div><div className="flex flex-wrap gap-3"><Link href={`/contact?subject=${encodeURIComponent(`${page.name} quote request`)}`} className="bg-white px-5 py-3 text-[12px] font-semibold text-[#173F31] no-underline">Request quote</Link><Link href={`/contact?subject=${encodeURIComponent(`${page.name} sample request`)}`} className="border border-white/25 px-5 py-3 text-[12px] font-semibold text-white no-underline">Request sample</Link><Link href="/downloads" className="border border-white/25 px-5 py-3 text-[12px] font-semibold text-white no-underline">Request documents</Link></div></div></Container></section>
  </>
}
